### ISSUE TITLE
More betas for the calculation

### ISSUE THREAD

**Issue by WeiWenKevinChen** [pyNLO/PyNLO#54]
I am trying to simulate supercontinuum output from different PCFs. However, I found that there are only beta_2 ~ beta_4 allowed to be entered. Is there anyway that I can put additional beta_5 and beta_6 for the calculation?

Thanks!

**Comment by ycasg** [comment]
You can go as high as you want with betas, there is no limit or hard coding
on the length of the expansion, see fiber.generate_fiber. You can also use
the fiber.load_from_file helper function to read in a tabulation of the
fiber dispersion.

**Comment by WeiWenKevinChen** [comment]
Thank you so much for your response. That helps me a lot! I appreciate it.
