### ISSUE TITLE
Error in sellmeier values from gayer publication

### ISSUE THREAD

**Issue by vfreysz** [pyNLO/PyNLO#55]
In https://github.com/pyNLO/PyNLO/blob/master/src/pynlo/media/crystals/XTAL_PPLN.py we can see that b4  = 1.526e-5.
But in Gayer publication Temperature and wavelength dependent refractive index equations for MgO-doped congruent and stoichiometric LiNbO3 (DOI:10.1007/s00340-008-2998-2) we can see that we should have b4  = 1.516e-4.
With that coefficient corrected, numerical simulations are in good agreement with my experiments.

**Comment by DanHickstein** [comment]
Good catch! I'd say you should make a PR and @ycasg will merge it.

**Comment by ycasg** [comment]
Fixed with edit to master branch. Thanks for pointing this out.
